const Map<String, String> ar = {
  // عام
  'app_name': 'كوزي',
  'loading': 'جاري التحميل...',
  'error': 'خطأ',
  'success': 'نجاح',
  'cancel': 'إلغاء',
  'confirm': 'تأكيد',
  'save': 'حفظ',
  'delete': 'حذف',
  'edit': 'تعديل',
  'add': 'إضافة',
  'search': 'بحث',
  'no_data': 'لا توجد بيانات',
  'yes': 'نعم',
  'no': 'لا',

  // التنقل
  'home': 'الرئيسية',
  'my_bookings': 'حجوزاتي',
  'favorites': 'المفضلة',
  'profile': 'حسابي',
  'my_apartments': 'شُقَقي',
  'booking_requests': 'الطلبات',

  // تسجيل الدخول
  'login': 'تسجيل الدخول',
  'logout': 'تسجيل الخروج',
  'register': 'إنشاء حساب',
  'phone': 'رقم الهاتف',
  'password': 'كلمة المرور',
  'confirm_password': 'تأكيد كلمة المرور',
  'first_name': 'الاسم الأول',
  'last_name': 'الاسم الأخير',
  'birth_date': 'تاريخ الميلاد',
  'forgot_password': 'نسيت كلمة المرور؟',
  'no_account': 'ليس لديك حساب؟',
  'have_account': 'لديك حساب بالفعل؟',
  'invalid_credentials': 'بيانات الدخول غير صحيحة',
  'login_success': 'تم تسجيل الدخول بنجاح',
  'logout_confirm': 'هل أنت متأكد من تسجيل الخروج؟',

  // التسجيل
  'register_as': 'التسجيل كـ',
  'owner': 'مالك',
  'renter': 'مستأجر',
  'personal_image': 'الصورة الشخصية',
  'id_image': 'صورة الهوية',
  'select_image': 'اختر صورة',
  'registration_success': 'تم التسجيل بنجاح، في انتظار الموافقة',

  // الشقق
  'apartments': 'الشقق',
  'available_apartments': 'الشقق المتاحة',
  'apartment_details': 'تفاصيل الشقة',
  'apartment_title': 'عنوان الشقة',
  'description': 'الوصف',
  'price_per_night': 'السعر / ليلة',
  'rooms': 'الغرف',
  'area': 'المساحة',
  'governorate': 'المحافظة',
  'city': 'المدينة',
  'images': 'الصور',
  'main_image': 'الصورة الرئيسية',
  'add_apartment': 'إضافة شقة',
  'edit_apartment': 'تعديل الشقة',
  'delete_apartment': 'حذف الشقة',
  'delete_apartment_confirm': 'هل تريد حذف هذه الشقة؟',
  'no_apartments': 'لا توجد شقق متاحة',
  'view_details': 'عرض التفاصيل',
  'sqm': 'م²',

  // البحث والفلترة
  'search_by': 'البحث حسب',
  'by_name': 'الاسم',
  'by_city': 'المدينة',
  'by_governorate': 'المحافظة',
  'by_price': 'السعر',
  'by_rooms': 'عدد الغرف',
  'change': 'تغيير',
  'enter_search': 'أدخل كلمة للبحث...',

  // الحجز
  'book_now': 'احجز الآن',
  'booking': 'الحجز',
  'booking_details': 'تفاصيل الحجز',
  'check_in': 'تاريخ الوصول',
  'check_out': 'تاريخ المغادرة',
  'nights': 'ليالي',
  'total': 'الإجمالي',
  'send_booking_request': 'إرسال طلب الحجز',
  'booking_success': 'تم إرسال طلب الحجز بنجاح',
  'booking_conflict': 'الشقة محجوزة في هذه الفترة',
  'select_dates': 'اختر التواريخ',
  'cannot_book_own': 'لا يمكنك حجز شقتك الخاصة',

  // حالات الحجز
  'pending': 'معلقة',
  'approved': 'مؤكدة',
  'cancelled': 'ملغية',
  'rejected': 'مرفوضة',
  'status': 'الحالة',
  'pending_status': 'في الانتظار',
  'approved_status': 'مؤكد',
  'cancelled_status': 'ملغي',
  'rejected_status': 'مرفوض',

  // إدارة الحجوزات
  'cancel_booking': 'إلغاء الحجز',
  'edit_booking': 'تعديل الحجز',
  'cancel_booking_confirm': 'هل تريد إلغاء هذا الحجز؟',
  'booking_cancelled': 'تم إلغاء الحجز',
  'booking_updated': 'تم تعديل الحجز',
  'modification_needs_approval': '* التعديل يحتاج موافقة المالك مرة أخرى',
  'no_bookings': 'لا توجد حجوزات',

  // طلبات الحجز (للمالك)
  'booking_requests_title': 'طلبات الحجز',
  'no_booking_requests': 'لا توجد طلبات حجز جديدة',
  'approve': 'قبول',
  'reject': 'رفض',
  'approve_booking': 'قبول الحجز',
  'reject_booking': 'رفض الحجز',
  'approve_confirm': 'هل تريد قبول هذا الحجز؟',
  'reject_confirm': 'هل تريد رفض هذا الحجز؟',
  'booking_approved': 'تم قبول الحجز بنجاح',
  'booking_rejected': 'تم رفض الحجز',
  'modification_request': 'طلب تعديل حجز',
  'new_dates_requested': 'التواريخ الجديدة المطلوبة',
  'approve_modification': 'قبول التعديل',
  'reject_modification': 'رفض التعديل',
  'from': 'من',
  'to': 'إلى',

  // المفضلة
  'favorites_title': 'المفضلة',
  'no_favorites': 'لا يوجد شقق في المفضلة حالياً',
  'added_to_favorites': 'تمت الإضافة للمفضلة',
  'removed_from_favorites': 'تمت الإزالة من المفضلة',

  // الملف الشخصي
  'profile_title': 'الملف الشخصي',
  'edit_profile': 'تعديل الملف الشخصي',
  'account_status': 'حالة الحساب',
  'active': 'مفعّل',
  'pending_approval': 'قيد الانتظار',
  'account_rejected': 'مرفوض',
  'admin': 'مدير',
  'user': 'مستخدم',
  'new_password': 'كلمة السر الجديدة',
  'leave_empty': 'اتركها فارغة إذا لا تريد التغيير',
  'password_min_length': 'كلمة السر يجب أن تكون 8 أحرف على الأقل',
  'password_mismatch': 'كلمة السر غير متطابقة',
  'changes_saved': 'تم حفظ التغييرات',

  // الإعدادات
  'settings': 'الإعدادات',
  'dark_mode': 'الوضع الليلي',
  'enabled': 'مفعّل',
  'disabled': 'معطّل',
  'language': 'اللغة',
  'arabic': 'العربية',
  'english': 'English',

  // لوحة الأدمن
  'admin_dashboard': 'لوحة التحكم',
  'pending_users': 'المستخدمين المعلقين',
  'pending_apartments': 'الشقق المعلقة',
  'approve_users': 'الموافقة على المستخدمين',
  'approve_apartments': 'الموافقة على الشقق',
  'no_pending_users': 'لا يوجد مستخدمين في انتظار الموافقة',
  'no_pending_apartments': 'لا يوجد شقق في انتظار الموافقة',
  'user_approved': 'تم قبول المستخدم',
  'user_rejected': 'تم رفض المستخدم',
  'apartment_approved': 'تم قبول الشقة',
  'apartment_rejected': 'تم رفض الشقة',
};