const Map<String, String> en = {
  // General
  'app_name': 'Cozy',
  'loading': 'Loading...',
  'error': 'Error',
  'success': 'Success',
  'cancel': 'Cancel',
  'confirm': 'Confirm',
  'save': 'Save',
  'delete': 'Delete',
  'edit': 'Edit',
  'add': 'Add',
  'search': 'Search',
  'no_data': 'No data available',
  'yes': 'Yes',
  'no': 'No',

  // Navigation
  'home': 'Home',
  'my_bookings': 'My Bookings',
  'favorites': 'Favorites',
  'profile': 'Profile',
  'my_apartments': 'My Apartments',
  'booking_requests': 'Requests',

  // Login
  'login': 'Login',
  'logout': 'Logout',
  'register': 'Register',
  'phone': 'Phone Number',
  'password': 'Password',
  'confirm_password': 'Confirm Password',
  'first_name': 'First Name',
  'last_name': 'Last Name',
  'birth_date': 'Birth Date',
  'forgot_password': 'Forgot Password?',
  'no_account': "Don't have an account?",
  'have_account': 'Already have an account?',
  'invalid_credentials': 'Invalid credentials',
  'login_success': 'Logged in successfully',
  'logout_confirm': 'Are you sure you want to logout?',

  // Registration
  'register_as': 'Register as',
  'owner': 'Owner',
  'renter': 'Renter',
  'personal_image': 'Personal Photo',
  'id_image': 'ID Photo',
  'select_image': 'Select Image',
  'registration_success': 'Registration successful, pending approval',

  // Apartments
  'apartments': 'Apartments',
  'available_apartments': 'Available Apartments',
  'apartment_details': 'Apartment Details',
  'apartment_title': 'Apartment Title',
  'description': 'Description',
  'price_per_night': 'Price / Night',
  'rooms': 'Rooms',
  'area': 'Area',
  'governorate': 'Governorate',
  'city': 'City',
  'images': 'Images',
  'main_image': 'Main Image',
  'add_apartment': 'Add Apartment',
  'edit_apartment': 'Edit Apartment',
  'delete_apartment': 'Delete Apartment',
  'delete_apartment_confirm': 'Do you want to delete this apartment?',
  'no_apartments': 'No apartments available',
  'view_details': 'View Details',
  'sqm': 'sqm',

  // Search & Filter
  'search_by': 'Search by',
  'by_name': 'Name',
  'by_city': 'City',
  'by_governorate': 'Governorate',
  'by_price': 'Price',
  'by_rooms': 'Rooms',
  'change': 'Change',
  'enter_search': 'Enter search keyword...',

  // Booking
  'book_now': 'Book Now',
  'booking': 'Booking',
  'booking_details': 'Booking Details',
  'check_in': 'Check-in Date',
  'check_out': 'Check-out Date',
  'nights': 'nights',
  'total': 'Total',
  'send_booking_request': 'Send Booking Request',
  'booking_success': 'Booking request sent successfully',
  'booking_conflict': 'Apartment is booked during this period',
  'select_dates': 'Select dates',
  'cannot_book_own': 'You cannot book your own apartment',

  // Booking Status
  'pending': 'Pending',
  'approved': 'Confirmed',
  'cancelled': 'Cancelled',
  'rejected': 'Rejected',
  'status': 'Status',
  'pending_status': 'Pending',
  'approved_status': 'Confirmed',
  'cancelled_status': 'Cancelled',
  'rejected_status': 'Rejected',

  // Booking Management
  'cancel_booking': 'Cancel Booking',
  'edit_booking': 'Edit Booking',
  'cancel_booking_confirm': 'Do you want to cancel this booking?',
  'booking_cancelled': 'Booking cancelled',
  'booking_updated': 'Booking updated',
  'modification_needs_approval': '* Modification needs owner approval',
  'no_bookings': 'No bookings',

  // Booking Requests (Owner)
  'booking_requests_title': 'Booking Requests',
  'no_booking_requests': 'No new booking requests',
  'approve': 'Approve',
  'reject': 'Reject',
  'approve_booking': 'Approve Booking',
  'reject_booking': 'Reject Booking',
  'approve_confirm': 'Do you want to approve this booking?',
  'reject_confirm': 'Do you want to reject this booking?',
  'booking_approved': 'Booking approved successfully',
  'booking_rejected': 'Booking rejected',
  'modification_request': 'Modification Request',
  'new_dates_requested': 'New Requested Dates',
  'approve_modification': 'Approve Modification',
  'reject_modification': 'Reject Modification',
  'from': 'From',
  'to': 'To',

  // Favorites
  'favorites_title': 'Favorites',
  'no_favorites': 'No apartments in favorites',
  'added_to_favorites': 'Added to favorites',
  'removed_from_favorites': 'Removed from favorites',

  // Profile
  'profile_title': 'Profile',
  'edit_profile': 'Edit Profile',
  'account_status': 'Account Status',
  'active': 'Active ✔',
  'pending_approval': 'Pending Approval',
  'account_rejected': 'Rejected',
  'admin': 'Admin',
  'user': 'User',
  'new_password': 'New Password',
  'leave_empty': 'Leave empty if you don\'t want to change',
  'password_min_length': 'Password must be at least 8 characters',
  'password_mismatch': 'Passwords do not match',
  'changes_saved': 'Changes saved',

  // Settings
  'settings': 'Settings',
  'dark_mode': 'Dark Mode',
  'enabled': 'Enabled',
  'disabled': 'Disabled',
  'language': 'Language',
  'arabic': 'العربية',
  'english': 'English',

  // Admin Dashboard
  'admin_dashboard': 'Admin Dashboard',
  'pending_users': 'Pending Users',
  'pending_apartments': 'Pending Apartments',
  'approve_users': 'Approve Users',
  'approve_apartments': 'Approve Apartments',
  'no_pending_users': 'No users pending approval',
  'no_pending_apartments': 'No apartments pending approval',
  'user_approved': 'User approved',
  'user_rejected': 'User rejected',
  'apartment_approved': 'Apartment approved',
  'apartment_rejected': 'Apartment rejected',
};